# Stage 1: Build the application
FROM maven:3.8.4-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Stage 2: Create the final image
FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080

# Set environment variables for the application
ARG DB_URL
ARG DB_USERNAME
ARG DB_PASSWORD
ARG JWT_JWK_SET_URI
ARG ALIYUN_LLM_API_KEY

ENV DB_URL=$DB_URL
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV JWT_JWK_SET_URI=$JWT_JWK_SET_URI
ENV ALIYUN_LLM_API_KEY=$ALIYUN_LLM_API_KEY

ENTRYPOINT ["java", "-jar", "app.jar"]
